services:
  postgres:
    image: postgres:17

    container_name: agrimind-postgres

    restart: unless-stopped

    environment:
      POSTGRES_DB: agrimind
      POSTGRES_USER: agrimind
      POSTGRES_PASSWORD: agrimind123

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: